import Link from "next/link";
import { ArrowLeft, CalendarDays, PencilLine, Pin } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DeleteNoteDialog } from "@/features/notes/delete-note-dialog";
import { formatNoteDate } from "@/features/notes/note-schema";
import type { NoteRecord } from "@/features/notes/note-types";

export function NoteDetail({ note }: { note: NoteRecord }) {
  return <div className="mx-auto max-w-4xl space-y-6"><Link href="/notes" className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-blue-600 dark:text-slate-400 dark:hover:text-blue-300"><ArrowLeft className="h-4 w-4" />Back to notes</Link><section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_20px_45px_rgba(15,23,42,0.06)] dark:border-slate-800 dark:bg-slate-900 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="neutral">{note.course?.courseCode ?? "Personal"}</Badge>{note.pinned ? <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-blue-700 dark:bg-blue-500/10 dark:text-blue-200"><Pin className="h-3 w-3" />Pinned</span> : null}</div><h1 className="mt-5 text-3xl font-semibold tracking-tight text-slate-900 dark:text-white sm:text-4xl">{note.title}</h1><div className="mt-4 flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400"><CalendarDays className="h-4 w-4" /><time dateTime={note.updatedAt}>Last edited {formatNoteDate(note.updatedAt)}</time></div></div><div className="flex shrink-0 gap-3"><Link href={`/notes/${note.id}/edit`}><Button variant="secondary"><PencilLine className="h-4 w-4" />Edit</Button></Link><DeleteNoteDialog noteId={note.id} title={note.title} /></div></div><div className="mt-10 border-t border-slate-200 pt-8 dark:border-slate-800"><p className="whitespace-pre-wrap text-base leading-8 text-slate-700 dark:text-slate-200 sm:text-lg">{note.content}</p></div></section><Card className="rounded-[24px] p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Note metadata</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500 dark:text-slate-400">Created</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{formatNoteDate(note.createdAt)}</p></div><div><p className="text-xs text-slate-500 dark:text-slate-400">Updated</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{formatNoteDate(note.updatedAt)}</p></div><div><p className="text-xs text-slate-500 dark:text-slate-400">Course</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{note.course?.title ?? "Personal workspace"}</p></div></div></Card></div>;
}