import Link from "next/link";
import { CalendarDays, Clock3, MapPin, PencilLine } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DeleteScheduleDialog } from "@/features/schedule/delete-schedule-dialog";
import { eventTypeLabels, formatTime, getDayLabel } from "@/features/schedule/schedule-schema";
import { eventColorClasses, type ScheduleEventRecord } from "@/features/schedule/schedule-types";

export function ScheduleDetail({ event }: { event: ScheduleEventRecord }) {
  const color = eventColorClasses[event.color as keyof typeof eventColorClasses] ?? eventColorClasses.blue;
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_20px_45px_rgba(15,23,42,0.06)] dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className={`absolute inset-y-0 left-0 w-2 ${color.split(" ")[0]}`} /><div className="flex flex-col gap-6 pl-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="neutral">{eventTypeLabels[event.eventType]}</Badge>{event.course ? <Badge variant="default">{event.course.courseCode}</Badge> : <Badge variant="neutral">Personal</Badge>}</div><h1 className="mt-4 text-3xl font-semibold tracking-tight text-slate-900 dark:text-white">{event.title}</h1><p className="mt-3 flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400"><CalendarDays className="h-4 w-4" />{getDayLabel(event.dayOfWeek)} · {formatTime(event.startTime)} – {formatTime(event.endTime)}</p></div><div className="flex gap-3"><Link href={`/schedule/${event.id}/edit`}><Button variant="secondary"><PencilLine className="h-4 w-4" />Edit</Button></Link><DeleteScheduleDialog eventId={event.id} title={event.title} /></div></div></section><div className="grid gap-6 md:grid-cols-3"><Card className="rounded-[24px] p-5 dark:bg-slate-900"><Clock3 className="h-5 w-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Time</p><p className="mt-1 text-base font-semibold text-slate-900 dark:text-white">{formatTime(event.startTime)} – {formatTime(event.endTime)}</p></Card><Card className="rounded-[24px] p-5 dark:bg-slate-900"><CalendarDays className="h-5 w-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Day</p><p className="mt-1 text-base font-semibold text-slate-900 dark:text-white">{getDayLabel(event.dayOfWeek)}</p></Card><Card className="rounded-[24px] p-5 dark:bg-slate-900"><MapPin className="h-5 w-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Location</p><p className="mt-1 text-base font-semibold text-slate-900 dark:text-white">{event.location || "No location added"}</p></Card></div><Card className="rounded-[24px] p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Linked course</p><p className="mt-3 text-sm text-slate-700 dark:text-slate-200">{event.course ? `${event.course.courseCode} · ${event.course.title}` : "Personal event without a linked course"}</p></Card></div>;
}