import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CreditCard, PencilLine } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DeleteExpenseDialog } from "@/features/expenses/delete-expense-dialog";
import { formatExpenseDate } from "@/features/expenses/expense-schema";
import { categoryColorClasses, type ExpenseRecord } from "@/features/expenses/expense-types";
import { formatPHP } from "@/lib/currency";

export function ExpenseDetail({ expense }: { expense: ExpenseRecord }) {
  const income = expense.type === "INCOME";
  return <div className="mx-auto max-w-4xl space-y-6"><Link href="/expenses" className="text-sm font-medium text-slate-500 hover:text-blue-600 dark:text-slate-400">Back to expenses</Link><section className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_20px_45px_rgba(15,23,42,0.06)] dark:border-slate-800 dark:bg-slate-900 sm:p-8"><div className={`absolute inset-y-0 left-0 w-2 ${categoryColorClasses[expense.category.color] ?? "bg-slate-500"}`} /><div className="flex flex-col gap-6 pl-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="neutral">{expense.category.name}</Badge><Badge variant={income ? "success" : "neutral"}>{income ? "Income" : "Expense"}</Badge></div><h1 className="mt-5 text-3xl font-semibold tracking-tight text-slate-900 dark:text-white">{expense.title}</h1><p className={`mt-4 flex items-center gap-2 text-3xl font-semibold ${income ? "text-emerald-600 dark:text-emerald-300" : "text-slate-900 dark:text-white"}`}>{income ? <ArrowUpRight className="h-6 w-6" /> : <ArrowDownLeft className="h-6 w-6 text-rose-500" />}{income ? "+" : "-"}{formatPHP(expense.amount)}</p></div><div className="flex gap-3"><Link href={`/expenses/${expense.id}/edit`}><Button variant="secondary"><PencilLine className="h-4 w-4" />Edit</Button></Link><DeleteExpenseDialog expenseId={expense.id} title={expense.title} /></div></div></section><div className="grid gap-4 md:grid-cols-3"><Card className="rounded-[24px] p-5 dark:bg-slate-900"><CalendarDays className="h-5 w-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500">Date</p><p className="mt-1 font-semibold text-slate-900 dark:text-white">{formatExpenseDate(expense.transactionDate)}</p></Card><Card className="rounded-[24px] p-5 dark:bg-slate-900"><CreditCard className="h-5 w-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500">Payment method</p><p className="mt-1 font-semibold text-slate-900 dark:text-white">{expense.paymentMethod}</p></Card><Card className="rounded-[24px] p-5 dark:bg-slate-900"><p className="text-xs text-slate-500">Category</p><p className="mt-3 font-semibold text-slate-900 dark:text-white">{expense.category.name}</p><span className={`mt-2 inline-block h-2 w-12 rounded-full ${categoryColorClasses[expense.category.color] ?? "bg-slate-500"}`} /></Card></div><Card className="rounded-[24px] p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">Notes</p><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700 dark:text-slate-200">{expense.notes || "No notes added."}</p></Card></div>;
}