import Link from "next/link";
import { CalendarClock, Clock3, PencilLine } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DeleteAssignmentDialog } from "@/features/assignments/delete-assignment-dialog";
import { formatAssignmentDate } from "@/features/assignments/assignment-schema";
import { PriorityBadge, StatusBadge } from "@/features/assignments/assignment-badges";
import { courseColorClasses, type AssignmentRecord } from "@/features/assignments/assignment-types";

export function AssignmentDetail({ assignment }: { assignment: AssignmentRecord }) {
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_20px_45px_rgba(15,23,42,0.06)] dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className={`absolute inset-y-0 left-0 w-2 ${courseColorClasses[assignment.course.color] ?? "bg-blue-500"}`} /><div className="flex flex-col gap-6 pl-2 sm:flex-row sm:items-end sm:justify-between"><div><Badge variant="neutral">{assignment.course.courseCode}</Badge><h1 className="mt-4 text-3xl font-semibold tracking-tight text-slate-900 dark:text-white">{assignment.title}</h1><div className="mt-4 flex flex-wrap items-center gap-2"><PriorityBadge priority={assignment.priority} /><StatusBadge status={assignment.status} /></div></div><div className="flex flex-wrap gap-3"><Link href={`/assignments/${assignment.id}/edit`}><Button variant="secondary"><PencilLine className="h-4 w-4" />Edit</Button></Link><DeleteAssignmentDialog assignmentId={assignment.id} title={assignment.title} courseCode={assignment.course.courseCode} /></div></div></section><div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_360px]"><Card className="rounded-[26px] p-5 dark:bg-slate-900 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Description</p><div className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-700 dark:text-slate-200">{assignment.description || "No description added for this assignment."}</div></Card><aside><Card className="rounded-[26px] p-5 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Assignment details</p><div className="mt-5 space-y-4"><div className="flex items-start gap-3"><CalendarClock className="mt-0.5 h-4 w-4 text-blue-600" /><div><p className="text-xs text-slate-500 dark:text-slate-400">Due</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{formatAssignmentDate(assignment.dueDate)}</p></div></div><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-4 w-4 text-blue-600" /><div><p className="text-xs text-slate-500 dark:text-slate-400">Created</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{formatAssignmentDate(assignment.createdAt)}</p></div></div><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-4 w-4 text-blue-600" /><div><p className="text-xs text-slate-500 dark:text-slate-400">Updated</p><p className="mt-1 text-sm font-medium text-slate-900 dark:text-white">{formatAssignmentDate(assignment.updatedAt)}</p></div></div><div className="border-t border-slate-200 pt-4 dark:border-slate-800"><p className="text-xs text-slate-500 dark:text-slate-400">Linked course</p><Link href={`/courses/${assignment.course.id}`} className="mt-1 block text-sm font-semibold text-blue-600 hover:text-blue-500">{assignment.course.courseCode} · {assignment.course.title}</Link></div></div></Card></aside></div></div>;
}